"""``/profile/projects`` — the one section that is not generated by the factory.

Projects carry ``skill_ids[]``, so create and patch have to resolve ids against the
catalogue and rewrite the join rows. That is the behaviour worth testing: an
unknown id must be a 404 rather than a silent skip, and a repeated id must not
become a 500 from the composite primary key.
"""

from __future__ import annotations

import pytest


def _create(api_client, account, **overrides) -> dict:
    payload = {"title": "Portfolio site", **overrides}
    response = api_client.post(
        "/api/v1/profile/projects", json=payload, headers=account.headers
    )
    assert response.status_code == 201, response.text
    return response.json()


def _ids(body: dict) -> list[str]:
    return [ref["skill_id"] for ref in body["skills"]]


# --- basics ------------------------------------------------------------------


def test_the_project_list_starts_empty(api_client, candidate) -> None:
    page = api_client.get("/api/v1/profile/projects", headers=candidate.headers).json()

    assert page["items"] == []
    assert page["total"] == 0


def test_a_project_is_created_and_listed(api_client, candidate) -> None:
    created = _create(
        api_client,
        candidate,
        description="A site",
        role="Designer",
        live_url="https://x.test",
    )

    assert created["title"] == "Portfolio site"
    assert created["description"] == "A site"
    assert created["skills"] == []

    page = api_client.get("/api/v1/profile/projects", headers=candidate.headers).json()
    assert page["total"] == 1
    assert [row["id"] for row in page["items"]] == [created["id"]]


def test_patch_leaves_untouched_fields_alone(api_client, candidate) -> None:
    created = _create(api_client, candidate, description="Keep me", role="Engineer")

    response = api_client.patch(
        f"/api/v1/profile/projects/{created['id']}",
        json={"title": "Renamed"},
        headers=candidate.headers,
    )

    assert response.status_code == 200, response.text
    body = response.json()
    assert body["title"] == "Renamed"
    assert body["description"] == "Keep me"
    assert body["role"] == "Engineer"


def test_a_project_is_deleted_once_then_404(api_client, candidate) -> None:
    created = _create(api_client, candidate)

    first = api_client.delete(
        f"/api/v1/profile/projects/{created['id']}", headers=candidate.headers
    )
    second = api_client.delete(
        f"/api/v1/profile/projects/{created['id']}", headers=candidate.headers
    )

    assert first.status_code == 204
    assert second.status_code == 404
    assert second.json()["error"]["code"] == "not_found"


def test_an_unknown_field_on_create_is_422(api_client, candidate) -> None:
    response = api_client.post(
        "/api/v1/profile/projects",
        json={"title": "Site", "stars": 10},
        headers=candidate.headers,
    )

    assert response.status_code == 422
    page = api_client.get("/api/v1/profile/projects", headers=candidate.headers).json()
    assert page["total"] == 0




# --- skill_ids ---------------------------------------------------------------


def test_skill_ids_are_resolved_against_the_catalogue(
    api_client, candidate, make_skill
) -> None:
    python = make_skill("Python")
    rust = make_skill("Rust")

    created = _create(api_client, candidate, skill_ids=[str(python.id), str(rust.id)])

    assert _ids(created) == [str(python.id), str(rust.id)]
    assert [ref["name"] for ref in created["skills"]] == ["Python", "Rust"]


def test_a_repeated_skill_id_is_collapsed_not_a_500(
    api_client, candidate, make_skill
) -> None:
    """The composite primary key would reject a duplicate; the request must not."""

    skill = make_skill("Python")

    created = _create(api_client, candidate, skill_ids=[str(skill.id), str(skill.id)])

    assert _ids(created) == [str(skill.id)]


def test_an_unknown_skill_id_is_404_and_creates_nothing(
    api_client, candidate, make_skill
) -> None:
    """Silently dropping it would let the client believe it had tagged the project."""

    known = make_skill("Python")

    response = api_client.post(
        "/api/v1/profile/projects",
        json={
            "title": "Site",
            "skill_ids": [str(known.id), "00000000-0000-0000-0000-000000000000"],
        },
        headers=candidate.headers,
    )

    assert response.status_code == 404, response.text
    assert response.json()["error"]["code"] == "not_found"
    page = api_client.get("/api/v1/profile/projects", headers=candidate.headers).json()
    assert page["total"] == 0


def test_a_patch_with_skill_ids_replaces_the_set(
    api_client, candidate, make_skill
) -> None:
    python = make_skill("Python")
    rust = make_skill("Rust")
    go = make_skill("Go")
    created = _create(api_client, candidate, skill_ids=[str(python.id), str(rust.id)])

    replaced = api_client.patch(
        f"/api/v1/profile/projects/{created['id']}",
        json={"skill_ids": [str(go.id)]},
        headers=candidate.headers,
    )
    assert replaced.status_code == 200, replaced.text
    assert _ids(replaced.json()) == [str(go.id)]

    # Absent means "leave it alone", not "clear it".
    untouched = api_client.patch(
        f"/api/v1/profile/projects/{created['id']}",
        json={"title": "New title"},
        headers=candidate.headers,
    )
    assert untouched.status_code == 200
    assert _ids(untouched.json()) == [str(go.id)]


def test_skill_ids_can_be_cleared_by_sending_an_empty_list(
    api_client, candidate, make_skill
) -> None:
    skill = make_skill("Python")
    created = _create(api_client, candidate, skill_ids=[str(skill.id)])

    cleared = api_client.patch(
        f"/api/v1/profile/projects/{created['id']}",
        json={"skill_ids": []},
        headers=candidate.headers,
    )

    assert cleared.status_code == 200, cleared.text
    assert cleared.json()["skills"] == []


def test_an_inverted_date_range_is_422(api_client, candidate) -> None:
    """ProjectCreate reuses the shared date check — a 422, never a 500."""

    response = api_client.post(
        "/api/v1/profile/projects",
        json={"title": "Site", "start_date": "2022-01-01", "end_date": "2020-01-01"},
        headers=candidate.headers,
    )

    assert response.status_code == 422, response.text


# --- guards ------------------------------------------------------------------


def test_another_users_project_is_404(api_client, candidate, other_candidate) -> None:
    theirs = _create(api_client, other_candidate)

    for response in (
        api_client.patch(
            f"/api/v1/profile/projects/{theirs['id']}",
            json={"title": "Mine now"},
            headers=candidate.headers,
        ),
        api_client.delete(
            f"/api/v1/profile/projects/{theirs['id']}", headers=candidate.headers
        ),
    ):
        assert response.status_code == 404, response.text

    left = api_client.get(
        "/api/v1/profile/projects", headers=other_candidate.headers
    ).json()
    assert left["total"] == 1


def test_an_employer_is_refused_projects(api_client, employer) -> None:
    response = api_client.get("/api/v1/profile/projects", headers=employer.headers)

    assert response.status_code == 403
    assert response.json()["error"]["code"] == "forbidden"


def test_projects_require_a_token(api_client) -> None:
    assert api_client.get("/api/v1/profile/projects").status_code == 401
    create = api_client.post("/api/v1/profile/projects", json={"title": "Site"})
    assert create.status_code == 401


def test_the_aggregate_lists_the_projects_it_was_asked_for(
    api_client, candidate
) -> None:
    created = _create(api_client, candidate, title="Capstone")

    body = api_client.get("/api/v1/profile", headers=candidate.headers).json()

    assert [row["id"] for row in body["projects"]] == [created["id"]]


@pytest.mark.parametrize("bad", ["nonsense", "00000000-0000-0000-0000-000000000000"])
def test_a_malformed_project_id_is_404(api_client, candidate, bad) -> None:
    response = api_client.delete(
        f"/api/v1/profile/projects/{bad}", headers=candidate.headers
    )

    assert response.status_code == 404
