"""Typed realtime events.

An event is a plain JSON object with a stable shape, so the mobile client can
parse one without knowing which backend domain produced it:

.. code-block:: json

    {
      "event_id": "0f3c…",
      "event_type": "system.ping",
      "occurred_at": "2026-10-01T18:00:00+00:00",
      "recipient_user_id": "…",
      "topic": null,
      "payload": {}
    }

Three decisions worth stating, because each is a place where the obvious choice
is wrong:

**`event_id` is generated by the publisher, not the database.** There is no
events table. A durable event log is what Postgres is for, and these events are
*transient notifications that something already committed*; replaying them from
a log would let a stale event outlive the row that caused it. Deduping on a
UUID generated at publish time is enough, because the client also upserts by
primary key.

**`recipient_user_id` is part of the envelope, not the channel name.** One
namespaced channel (``mahaa:realtime``) carries everything; each instance
decides locally whether it holds a socket for that recipient. Per-user channels
would multiply subscriptions by the user count and buy nothing, since every
instance must see every event anyway to route it.

**`topic` is nullable and unused in this phase.** It exists so the messaging
phase can address a conversation without redesigning the envelope. It is not
authorisation: nothing may subscribe by topic yet.

**Phase 12 added the one exception to "untargeted means nobody".** An event in
:data:`BROADCAST_EVENT_TYPES` with no recipient is a fan-out to every connected
member. The decision is made once, in the event vocabulary, by the domains that
own the audience — and it matches what REST already authorises, because
``GET /posts`` and ``GET /stories`` are readable by any authenticated member. A
broadcast is still only a *notification*: the payload carries identifiers, and
the client re-fetches the authoritative row over REST.
"""

from __future__ import annotations

import json
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from typing import Any


class EventType:
    """The event types this phase ships.

    Only connection lifecycle and transport health. Business events —
    ``message.created``, ``notification.created``, call signalling — belong to
    later phases, and naming them here would invite the mobile client to handle
    something the backend does not yet emit.
    """

    CONNECTION_OPENED = "connection.opened"
    CONNECTION_CLOSED = "connection.closed"
    SYSTEM_PING = "system.ping"
    SYSTEM_ERROR = "system.error"

    #: Phase 2 — messaging. ``message.created`` is published only after the
    #: message transaction commits; ``conversation.read`` only after the read
    #: pointer commits. Both are *notifications that something already
    #: persisted*, never a carrier for state the client must trust.
    MESSAGE_CREATED = "message.created"
    CONVERSATION_READ = "conversation.read"

    #: Phase 3 — notifications. Published only after the transaction that
    #: produced the row commits. The payload is the *stored* notification's own
    #: public shape, so the client renders from the same fields REST returns.
    NOTIFICATION_CREATED = "notification.created"

    #: Phase 12 — content. ``post.created`` / ``story.created`` are published
    #: **after** the post or story transaction commits, and are **untargeted**:
    #: see :data:`BROADCAST_EVENT_TYPES`.
    #:
    #: ``post.updated`` / ``post.deleted`` exist so a reader's cached copy of a
    #: card cannot outlive the row it describes — a soft-deleted post is gone
    #: from every REST read, so without these a reader would keep rendering it
    #: until they pulled to refresh.
    POST_CREATED = "post.created"
    POST_UPDATED = "post.updated"
    POST_DELETED = "post.deleted"
    STORY_CREATED = "story.created"


#: Every type this build can produce. An inbound event outside this set is
#: rejected rather than forwarded, so a future publisher cannot accidentally
#: push an unhandled type at a client.
KNOWN_EVENT_TYPES: frozenset[str] = frozenset(
    {
        EventType.CONNECTION_OPENED,
        EventType.CONNECTION_CLOSED,
        EventType.SYSTEM_PING,
        EventType.SYSTEM_ERROR,
        EventType.MESSAGE_CREATED,
        EventType.CONVERSATION_READ,
        EventType.NOTIFICATION_CREATED,
        EventType.POST_CREATED,
        EventType.POST_UPDATED,
        EventType.POST_DELETED,
        EventType.STORY_CREATED,
    }
)

#: The types that go to **every connected member** rather than to one recipient.
#:
#: Phase 1 dropped every untargeted event, and the reason given was that
#: "broadcasting would mean the publisher had decided every connected user
#: should see it, which is a later-phase decision that must be made with
#: knowledge of the audience". This is that decision, and it is narrow:
#:
#: * ``GET /posts`` is readable by *any* authenticated member and is not scoped
#:   by connections (`services.posts.list_posts` applies no social-graph
#:   filter), so **every** member is already entitled to know a post exists.
#:   Targeting only connected users would leave a public post invisible in
#:   realtime to exactly the people who can read it over REST.
#: * ``GET /stories`` is the same: §10.1 states there is no per-viewer story
#:   ACL in V1.
#:
#: So the audience is "every connected member", which is what REST already
#: authorises. **The payload stays a notification**: an id, the author id and a
#: timestamp. It carries no media bytes, no token and no profile data, and the
#: client must answer it by re-fetching the authoritative row over REST — the
#: socket is an optimisation, PostgreSQL remains the source of truth.
#:
#: A future per-viewer content visibility rule changes this set, and nothing
#: else: the hub routes on membership of this frozenset rather than on a
#: decision made per socket.
BROADCAST_EVENT_TYPES: frozenset[str] = frozenset(
    {
        EventType.POST_CREATED,
        EventType.POST_UPDATED,
        EventType.POST_DELETED,
        EventType.STORY_CREATED,
    }
)

#: The single Redis channel every instance subscribes to. See the module
#: docstring for why this is one channel rather than one per user or topic.
REDIS_CHANNEL = "mahaa:realtime"


class RealtimeError(ValueError):
    """An event could not be built or read.

    Deliberately separate from ``TokenError`` and ``ApiError``: this is a
    transport-level fault, never a request the caller can fix by changing a
    field.
    """


@dataclass(frozen=True, slots=True)
class RealtimeEvent:
    """One event, immutable once built.

    ``frozen=True`` because an event may be handed to several sockets and to
    the Redis publisher at once; a mutating field would let one recipient's
    handling corrupt another's.
    """

    event_type: str
    payload: dict[str, Any] = field(default_factory=dict)
    recipient_user_id: str | None = None
    topic: str | None = None
    event_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    occurred_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def __post_init__(self) -> None:
        if self.event_type not in KNOWN_EVENT_TYPES:
            raise RealtimeError(f"Unknown realtime event type: {self.event_type!r}")

    @classmethod
    def system_ping(cls) -> RealtimeEvent:
        """A heartbeat. The client answers with ``system.pong``, which is not an
        event type — it is transport-level and never published onward."""
        return cls(event_type=EventType.SYSTEM_PING)

    def to_json(self) -> str:
        """Serialise for a WebSocket frame or a Redis message."""
        return json.dumps(self.to_dict(), separators=(",", ":"))

    def to_dict(self) -> dict[str, Any]:
        return {
            "event_id": self.event_id,
            "event_type": self.event_type,
            "occurred_at": self.occurred_at,
            "recipient_user_id": self.recipient_user_id,
            "topic": self.topic,
            "payload": self.payload,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> RealtimeEvent:
        """Rebuild an event received from Redis or a client.

        Tolerant about *shape* and strict about *meaning*: a missing optional
        key is filled in, but an unknown type or a missing id is rejected,
        because a client that cannot dedupe by ``event_id`` would replay the
        same message forever.
        """
        if not isinstance(data, dict):
            raise RealtimeError("Realtime event must be a JSON object.")

        event_type = data.get("event_type")
        if not isinstance(event_type, str):
            raise RealtimeError("Realtime event is missing 'event_type'.")

        payload = data.get("payload") or {}
        if not isinstance(payload, dict):
            raise RealtimeError("Realtime event 'payload' must be an object.")

        return cls(
            event_type=event_type,
            payload=payload,
            recipient_user_id=_optional_str(data.get("recipient_user_id")),
            topic=_optional_str(data.get("topic")),
            event_id=_required_id(data.get("event_id")),
            occurred_at=_optional_str(data.get("occurred_at")) or _now(),
        )

    def is_for(self, user_id: str) -> bool:
        """Whether this event is addressed to ``user_id``.

        An event with no recipient belongs to nobody through this method: it is
        a *broadcast*, and whether one exists is decided by
        :data:`BROADCAST_EVENT_TYPES` in the hub rather than here. ``is_for``
        stays the narrow question it has always been — "does this event name
        me?" — so adding a broadcast type cannot quietly widen what a targeted
        lookup returns.
        """
        return self.recipient_user_id is not None and self.recipient_user_id == user_id


def _optional_str(value: Any) -> str | None:
    return value if isinstance(value, str) and value else None


def _required_id(value: Any) -> str:
    if not isinstance(value, str) or not value:
        raise RealtimeError("Realtime event is missing 'event_id'.")
    return value


def _now() -> str:
    return datetime.now(UTC).isoformat()
