"""Phase 4 — connections.

One table: the relationship between two accounts. ``POST /connections``,
``accept``/``decline``/``cancel`` and ``DELETE /connections/{id}`` are the whole
surface, and the mobile client calls all six operations.

**Why a new table rather than a new revision on Phase 1.** Phase 1 deliberately
built the floor and stopped; its own docstring lists connections among the tables
it left to a later phase, because nothing in Phase 1 depends on one. This
revision therefore adds a table and touches nothing Phase 1 created.

**The unique index is the important line.** It is on
``(LEAST(requester_id, addressee_id), GREATEST(requester_id, addressee_id))``,
not on the two columns in order, so "A→B" and "B→A" collide. That is what makes a
duplicate request impossible under concurrency rather than merely unlikely: two
clients can both pass an application-level "does this already exist?" check, and
the second INSERT still fails here.

**Three invariants live in the database, not in Python.**

* ``requester_id <> addressee_id`` — no self-connection, even for a code path
  that forgot to check.
* ``status`` is a closed ``CHECK`` over the four stored values, so no route can
  write a status the state machine cannot reach. There is no ``PATCH`` verb, and
  deliberately no way to set a status to an arbitrary string.
* ``(status = 'pending') = (responded_at IS NULL)`` — pending is the only state
  with no timestamp, so those two columns can never disagree.

Reversible: ``downgrade`` drops the three indexes and the table, and touches no
other object.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '1e1990c37405'
down_revision: str | None = '7d162daa433c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'declined', 'canceled', name='connection_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'pending') = (responded_at IS NULL)", name=op.f('ck_connections_responded_at_matches_pending')),
    sa.CheckConstraint('requester_id <> addressee_id', name=op.f('ck_connections_no_self_connection')),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], name=op.f('fk_connections_addressee_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name=op.f('fk_connections_requester_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections')),
    comment='One row per unordered pair of users; see the unique index.'
    )
    op.create_index('ix_connections_addressee_id_status', 'connections', ['addressee_id', 'status'], unique=False)
    op.create_index('ix_connections_requester_id_status', 'connections', ['requester_id', 'status'], unique=False)
    op.create_index('uq_connections_requester_id_addressee_id', 'connections', [sa.literal_column('least(requester_id, addressee_id)'), sa.literal_column('greatest(requester_id, addressee_id)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_connections_requester_id_addressee_id', table_name='connections')
    op.drop_index('ix_connections_requester_id_status', table_name='connections')
    op.drop_index('ix_connections_addressee_id_status', table_name='connections')
    op.drop_table('connections')
    # ### end Alembic commands ###
