"""Phase 5 — messaging.

Three tables, and the two uniqueness rules that carry the whole domain:

* ``conversations.direct_key`` is ``min:max`` of the two participants' internal
  ids, UNIQUE and NULLABLE. UNIQUE makes a 1:1 conversation a property of the
  *data* rather than of a "does one already exist?" check, which is what makes
  two simultaneous ``POST /conversations`` for the same pair safe without a
  serialisable transaction. NULLABLE means a future group conversation needs no
  migration — the index simply stops applying to it.
* ``messages`` is UNIQUE on ``(conversation_id, sender_id, client_message_id)``,
  which is §18's idempotency mechanism. PostgreSQL treats NULLs as distinct, so
  ordinary messages and client-keyed ones coexist.

Three delete behaviours, each chosen rather than defaulted:

* ``messages.sender_id`` is **RESTRICT**. CASCADE would let an account deletion
  silently remove a conversation somebody else is still reading.
* ``conversations.created_by`` is **RESTRICT**, for the same reason: a thread
  whose creator row vanished is an orphan nobody can name.
* ``conversation_id`` and ``conversation_members.user_id`` are **CASCADE**. A
  conversation has no meaning without its messages, and a membership row has no
  meaning without the conversation.

**No foreign key on ``media_id``, ``last_message_id`` or
``last_read_message_id``.** The first points at ``media_assets``, which does not
exist until the media phase — a constraint may not reference an absent table, and
Phase 1 set the same precedent with ``users.avatar_media_id``. The other two would
be circular (a conversation referencing a message inside itself) and are validated
in the service layer, where "this message is really in this conversation" is
already known.

Reversible: ``downgrade`` drops the three indexes and the three tables in reverse
dependency order, and touches no object created by an earlier phase.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '744983a39587'
down_revision: str | None = '1e1990c37405'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_id', sa.UUID(), nullable=True),
    sa.Column('direct_key', sa.String(length=73), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversations_created_by_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('direct_key', name=op.f('uq_conversations_direct_key')),
    comment='One thread. direct_key makes it 1:1 in V1; NULL allows groups.'
    )
    op.create_index('ix_conversations_last_message_at', 'conversations', [sa.literal_column('(last_message_at) DESC NULLS LAST')], unique=False)
    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_read_message_id', sa.UUID(), nullable=True),
    sa.Column('muted', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('archived', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_members_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversation_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id', name=op.f('pk_conversation_members'))
    )
    op.create_index('ix_conversation_members_user_id_conversation_id', 'conversation_members', ['user_id', 'conversation_id'], unique=False)
    op.create_table('messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('client_message_id', sa.String(length=100), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], name=op.f('fk_messages_deleted_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('fk_messages_sender_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages')),
    sa.UniqueConstraint('conversation_id', 'sender_id', 'client_message_id', name='uq_messages_conversation_id_sender_id_client_message_id')
    )
    op.create_index('ix_messages_conversation_id_created_at_id', 'messages', ['conversation_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_conversation_id_created_at_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_conversation_members_user_id_conversation_id', table_name='conversation_members')
    op.drop_table('conversation_members')
    op.drop_index('ix_conversations_last_message_at', table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
