"""Phase 1 — database foundation.

The first real schema revision: the account row, the profile aggregate, the
skill catalogue, and the five profile-section tables. Nothing here is used by a
route yet — this phase builds the floor, and later phases build on it.

Scope decisions, so the boundary is auditable:

* **No token tables.** ``email_verifications`` and ``password_reset_tokens``
  belong to the authentication phase, and ``refresh_tokens`` is conditional on a
  token-strategy decision that has not been made. Creating them now would be
  building Phase 2.
* **No media table.** ``users.avatar_media_id`` exists as a nullable uuid with
  no foreign key, because a constraint may not reference a table that does not
  exist yet. The media phase adds the table and the FK together.
* **No conversations, messages, calls, notifications, posts, stories,
  opportunities, companies or institutions.** Each of those is a later phase, and
  none is a dependency of the tables here.

``citext`` is created first and unconditionally with ``IF NOT EXISTS``. It is
required by ``users.email`` for case-insensitive uniqueness, and autogenerate
cannot emit an extension, so without this line the migration would fail on a
database where the extension is absent.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "7d162daa433c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Must run before `users` is created: `users.email` is CITEXT, and a CITEXT
    # column cannot be created in a database where the type does not exist.
    # `IF NOT EXISTS` makes this safe to re-run against a database that already
    # has it, which is the normal case for a shared Neon project.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills')),
    sa.UniqueConstraint('name', name=op.f('uq_skills_name')),
    comment='Global skill catalogue backing GET /skills/catalog.'
    )
    op.create_index('ix_skills_category', 'skills', ['category'], unique=False)
    op.create_table('users',
    sa.Column('public_id', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.Enum('candidate', 'employer', 'college', 'admin', name='user_role', native_enum=False, create_constraint=True), server_default='candidate', nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deactivated', name='user_status', native_enum=False, create_constraint=True), server_default='active', nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('avatar_media_id', sa.UUID(), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    comment='One Mahaa account. Public-facing identity is public_id.'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('achievements',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('competition', 'award', 'academic', 'hackathon', 'publication', 'leadership', name='achievement_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('achieved_on', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_achievements_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_achievements'))
    )
    op.create_index('ix_achievements_user_id', 'achievements', ['user_id'], unique=False)
    op.create_index('ix_achievements_user_id_category', 'achievements', ['user_id', 'category'], unique=False)
    op.create_table('certifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('issuer', sa.String(length=200), nullable=False),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=120), nullable=True),
    sa.Column('verification_url', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('expires_on IS NULL OR issued_on IS NULL OR expires_on >= issued_on', name=op.f('ck_certifications_certification_dates_ordered')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_certifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_index('ix_certifications_user_id', 'certifications', ['user_id'], unique=False)
    op.create_table('education',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=False),
    sa.Column('degree', sa.String(length=200), nullable=True),
    sa.Column('field_of_study', sa.String(length=200), nullable=True),
    sa.Column('level', sa.Enum('school', 'diploma', 'undergraduate', 'postgraduate', 'doctorate', 'other', name='education_level', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('grade', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT current OR end_date IS NULL', name=op.f('ck_education_education_current_is_open')),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_education_education_dates_ordered')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_education_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education'))
    )
    op.create_index('ix_education_user_id_start_date', 'education', ['user_id', 'start_date'], unique=False)
    op.create_table('experience',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_mode', sa.Enum('remote', 'hybrid', 'onsite', name='experience_work_mode', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('current', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT current OR end_date IS NULL', name=op.f('ck_experience_experience_current_is_open')),
    sa.CheckConstraint('end_date IS NULL OR start_date IS NULL OR end_date >= start_date', name=op.f('ck_experience_experience_dates_ordered')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_experience_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experience'))
    )
    op.create_index('ix_experience_user_id_start_date', 'experience', ['user_id', 'start_date'], unique=False)
    op.create_table('profile_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile_links')),
    sa.UniqueConstraint('user_id', 'kind', name='uq_profile_links_user_id_kind')
    )
    op.create_table('profile_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('work_modes', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('employment_types', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('preferred_locations', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='INR', nullable=False),
    sa.Column('availability_date', sa.Date(), nullable=True),
    sa.Column('willing_to_relocate', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_max >= salary_min', name=op.f('ck_profile_preferences_salary_range_ordered')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profile_preferences')),
    comment='Job-search preferences. Absent row means never set.'
    )
    op.create_table('profile_privacy',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_visibility', sa.Enum('private', 'employers', 'public', name='profile_visibility', native_enum=False, create_constraint=True), server_default='private', nullable=False),
    sa.Column('discoverable', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_messages', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_email', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('show_phone', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profile_privacy_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profile_privacy')),
    comment='Per-user privacy settings. One row per user.'
    )
    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles')),
    comment='Free-text profile. One row per user, keyed by user_id.'
    )
    op.create_table('projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=120), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('live_url', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_projects_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index('ix_projects_user_id', 'projects', ['user_id'], unique=False)
    op.create_table('user_skills',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', 'expert', name='skill_level', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_user_skills_skill_id_skills'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_skills_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_skills')),
    sa.UniqueConstraint('user_id', 'skill_id', name='uq_user_skills_user_id_skill_id')
    )
    op.create_index('ix_user_skills_skill_id', 'user_skills', ['skill_id'], unique=False)
    op.create_index('ix_user_skills_user_id', 'user_skills', ['user_id'], unique=False)
    op.create_table('project_skills',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_skills_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], name=op.f('fk_project_skills_skill_id_skills'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('project_id', 'skill_id', name=op.f('pk_project_skills'))
    )
    op.create_index('ix_project_skills_skill_id', 'project_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_skills_skill_id', table_name='project_skills')
    op.drop_table('project_skills')
    op.drop_index('ix_user_skills_user_id', table_name='user_skills')
    op.drop_index('ix_user_skills_skill_id', table_name='user_skills')
    op.drop_table('user_skills')
    op.drop_index('ix_projects_user_id', table_name='projects')
    op.drop_table('projects')
    op.drop_table('profiles')
    op.drop_table('profile_privacy')
    op.drop_table('profile_preferences')
    op.drop_table('profile_links')
    op.drop_index('ix_experience_user_id_start_date', table_name='experience')
    op.drop_table('experience')
    op.drop_index('ix_education_user_id_start_date', table_name='education')
    op.drop_table('education')
    op.drop_index('ix_certifications_user_id', table_name='certifications')
    op.drop_table('certifications')
    op.drop_index('ix_achievements_user_id_category', table_name='achievements')
    op.drop_index('ix_achievements_user_id', table_name='achievements')
    op.drop_table('achievements')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_skills_category', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###

    # Last, because nothing uses it once every table is gone. Dropping the
    # extension keeps `downgrade` a true inverse of `upgrade`; leaving it behind
    # would make this revision non-reversible. It is safe here only because this
    # revision is the sole owner of `citext` in this schema — if a later phase
    # adds a CITEXT column outside this revision, this statement has to be
    # revisited in the same change.
    op.execute("DROP EXTENSION IF EXISTS citext")

