"""Institutions and programs â€” Â§12.3's college workspace, Â§14.9's two tables.

Follows ``d7e4c1a9f2b8`` (Phase 10 user devices).

**Â§1906 assigns institutions to Phase 9, but Phase 9 did not ship them.**
``b3f8a1c07d54`` is titled "Phase 9 â€” companies, opportunities, and the story links
Phase 8 deferred" and created ``companies``, ``company_members``, ``opportunities``
and ``opportunity_requirements``. Â§14.9 describes ``institutions`` and ``programs`` in
the very same data dictionary section, so the omission was Phase 9's, not a decision
to defer. This revision adds them rather than editing a revision that has already run
in other environments. Hence "Phase 11" in the filename: it is the eleventh revision
in the chain, not a claim that the specification renumbered the phases.

**``institutions`` is ``companies`` plus ``owner_id``, and that is the whole
difference.** Â§14.9 says so in one line. The column set is therefore identical â€”
including ``industry`` and ``company_size``, which no client reads today (Â§12.3's
wire type omits both) but which Â§14.9 specifies. A narrower table now would mean a
second migration the first time a client does read them.

**``owner_id`` is RESTRICT and NOT NULL.** RESTRICT because Â§14.9 says so, and because
an institution is the workspace of a real person â€” deleting that person must not take
a college's public record and every program attached to it along with the account. NOT
NULL because Â§12.3 makes *every* route ownership-scoped, so an institution with no
owner would be a row no route could ever reach.

**``programs.institution_id`` is CASCADE**, the opposite of ``owner_id``, and
deliberately so. A program has no meaning without the institution that offers it. A
CASCADE on the owner would have turned an account deletion into an unreviewed bulk
delete of an organisation's catalogue.

**``programs`` has no ``CHECK (btrim(name) <> '')``** even though ``companies`` and
``institutions`` do. Â§14.9 enumerates programs as "``name text NOT NULL`` Â· ``level``
text NULL Â· ``description`` text NULL Â· timestamps. Index ``(institution_id)``" and
names no constraint. NOT NULL is enforced by the column; a blank name is refused by
the request schema with a 422 that names the field.

**No destructive operation, and no unrelated change.** This revision creates exactly
two tables and their indexes, and ``downgrade`` drops exactly those.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "a1c94f7b2e08"
down_revision: str | None = "d7e4c1a9f2b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> sa.Enum:
    """A ``VARCHAR`` + CHECK, matching ``models.enums.pg_enum`` everywhere else."""
    return sa.Enum(*values, name=name, native_enum=False, create_constraint=True)


def upgrade() -> None:
    op.create_table(
        "institutions",
        sa.Column("name", sa.String(length=200), nullable=False),
        # Server-generated by the service and never writable; Â§12.3 calls it
        # "server-owned" exactly as Â§12.2 does for companies.
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        # Â§14.9's "as companies". Not on the wire today; see the module docstring.
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column(
            "company_size",
            _enum(
                "company_size",
                "1-10",
                "11-50",
                "51-200",
                "201-500",
                "501-1000",
                "1000+",
            ),
            nullable=True,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        # Â§14.11's reference check reaches this column, as it does for companies.
        sa.Column("logo_media_id", sa.UUID(), nullable=True),
        # Server-owned: absent from every write schema (Â§12.3).
        sa.Column(
            "verification_status",
            _enum(
                "verification_status",
                "unverified",
                "pending",
                "verified",
                "rejected",
            ),
            nullable=False,
            server_default="unverified",
        ),
        sa.Column(
            "status",
            _enum("status", "active", "inactive"),
            nullable=False,
            server_default="active",
        ),
        # Â§14.9: the registering contact person. RESTRICT â€” see the module docstring.
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        # Carried over from companies because Â§14.9 defines institutions as
        # "as `companies`".
        sa.CheckConstraint(
            "btrim(name) <> ''", name=op.f("ck_institutions_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["logo_media_id"],
            ["media_assets.id"],
            name=op.f("fk_institutions_logo_media_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_institutions_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_institutions")),
        sa.UniqueConstraint("slug", name=op.f("uq_institutions_slug")),
    )
    # Every Â§12.3 route is filtered by owner_id, so this is the read path, not an
    # optimisation. Mirrors companies' status index for the same reason.
    op.create_index(
        "ix_institutions_owner_id", "institutions", ["owner_id"], unique=False
    )
    op.create_index("ix_institutions_status", "institutions", ["status"], unique=False)

    op.create_table(
        "programs",
        sa.Column("institution_id", sa.UUID(), nullable=False),
        # Â§14.9: "name text NOT NULL". No CHECK â€” see the module docstring.
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("level", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        # CASCADE, the opposite of institutions.owner_id â€” see the module docstring.
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institutions.id"],
            name=op.f("fk_programs_institution_id_institutions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_programs")),
    )
    # Â§14.9 names this index, and it is also the only query path programs are read by.
    op.create_index(
        "ix_programs_institution_id", "programs", ["institution_id"], unique=False
    )


def downgrade() -> None:
    """Remove only what ``upgrade`` created.

    ``programs`` first: it references ``institutions``, so dropping the parent first
    would leave a dangling constraint. Indexes go with their tables, so they are not
    dropped separately.
    """
    op.drop_index("ix_programs_institution_id", table_name="programs")
    op.drop_table("programs")

    op.drop_index("ix_institutions_status", table_name="institutions")
    op.drop_index("ix_institutions_owner_id", table_name="institutions")
    op.drop_table("institutions")
