"""Phase 9 — companies, opportunities, and the story links Phase 8 deferred.

Follows ``5d1c74ab9e02`` (Phase 8 stories). It **adds** ``stories.company_id`` and
``stories.opportunity_id`` rather than recreating ``stories``, so the two story rows a
developer may already have written survive untouched and the FKs start as NULL.

**The §14.10 story CHECK is added here, and it is why this revision exists.** Phase 8
could not write ``CHECK (publisher_kind = 'company') = (company_id IS NOT NULL)`` because
``companies`` did not exist, so it refused a company story at the service layer instead.
This migration creates the table, adds the column, and moves that rule into the
database where it can no longer be bypassed. Existing ``platform`` rows satisfy the
CHECK immediately (``'platform' = 'company'`` is false, and their ``company_id`` is NULL).

**Both story FKs are SET NULL, and that is load-bearing for the CHECK.** A CASCADE
would try to delete the story row before PostgreSQL could evaluate anything, and a
RESTRICT would make a company undeletable while an announcement still cited it. SET
NULL leaves a platform-kind story behind — but the CHECK would then fail, so the
service converts a doomed company story to ``platform`` *before* the delete runs.
See ``services/companies.py``.

**``companies.logo_media_id`` is RESTRICT**, matching ``post_media.media_id`` and
``stories.media_id``: an asset a reachable company shows must not be deletable out from
under it, and §14.11's reference check now covers it.

**``opportunities.company_id`` is RESTRICT too**, per §14.9. A posting must remain
explainable after an employer workspace is removed; CASCADE would silently delete live
postings.

**The partial unique index on ``company_members`` is partial** (``WHERE role =
'owner'``), not a plain unique on ``company_id``: "at most one owner per company" must
not become "at most one member of any kind". §14.9 asks for exactly this, and a company
with three recruiters has to be representable.

**An invite cannot mint an owner, and this is deliberately *not* a CHECK.** §14.9 says
so: "the table must still be able to *represent* an owner, so the prohibition is not a
table CHECK". Promoting an existing member to owner is legitimate; only the invite path
is restricted, and only the service can tell those apart.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "b3f8a1c07d54"
down_revision: str | None = "5d1c74ab9e02"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> sa.Enum:
    """A ``VARCHAR`` + CHECK, matching ``models.enums.pg_enum`` everywhere else."""
    return sa.Enum(*values, name=name, native_enum=False, create_constraint=True)


def upgrade() -> None:
    op.create_table(
        "companies",
        sa.Column("name", sa.String(length=200), nullable=False),
        # Server-generated by the service and never writable; §12.2 calls it
        # "server-owned".
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column(
            "company_size",
            _enum(
                "company_size",
                "1-10",
                "11-50",
                "51-200",
                "201-500",
                "501-1000",
                "1000+",
            ),
            nullable=True,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        # §14.11's reference check reaches this column; see the module docstring.
        sa.Column("logo_media_id", sa.UUID(), nullable=True),
        # Server-owned: absent from every write schema (§12.2).
        sa.Column(
            "verification_status",
            _enum(
                "verification_status",
                "unverified",
                "pending",
                "verified",
                "rejected",
            ),
            nullable=False,
            server_default="unverified",
        ),
        sa.Column(
            "status",
            _enum("company_status", "active", "inactive"),
            nullable=False,
            server_default="active",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "btrim(name) <> ''", name=op.f("ck_companies_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["logo_media_id"],
            ["media_assets.id"],
            name=op.f("fk_companies_logo_media_id_media_assets"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_companies")),
        sa.UniqueConstraint("slug", name=op.f("uq_companies_slug")),
    )
    op.create_index("ix_companies_status", "companies", ["status"], unique=False)

    op.create_table(
        "company_members",
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "role",
            _enum(
                "company_member_role",
                "owner",
                "admin",
                "recruiter",
                "hiring_manager",
                "viewer",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            _enum("company_member_status", "invited", "active", "suspended"),
            nullable=False,
            server_default="invited",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_company_members_company_id_companies"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_company_members_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company_members")),
        # §14.9's unique (company_id, user_id): a second invite is a conflict the
        # database can name, not a duplicate row.
        sa.UniqueConstraint("company_id", "user_id", name="uq_company_members_pair"),
    )
    # §14.9's partial unique index. See the module docstring for why it is partial.
    op.create_index(
        "uq_company_members_one_owner",
        "company_members",
        ["company_id"],
        unique=True,
        postgresql_where=sa.text("role = 'owner'"),
    )
    # `/companies/mine` resolves from the token on every call.
    op.create_index(
        "ix_company_members_user_id_status",
        "company_members",
        ["user_id", "status"],
        unique=False,
    )

    op.create_table(
        "opportunities",
        # §14.9: FK companies **RESTRICT** — a posting stays explainable after the
        # workspace goes. See the module docstring.
        sa.Column("company_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=250), nullable=False),
        sa.Column("slug", sa.String(length=280), nullable=False),
        sa.Column(
            "opportunity_type",
            _enum(
                "opportunity_type",
                "job",
                "internship",
                "apprenticeship",
                "project_gig",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            _enum("opportunity_status", "draft", "published", "closed"),
            nullable=False,
            server_default="draft",
        ),
        sa.Column(
            "visibility",
            _enum("opportunity_visibility", "public", "unlisted"),
            nullable=False,
            server_default="public",
        ),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("responsibilities", sa.Text(), nullable=True),
        sa.Column("requirements_text", sa.Text(), nullable=True),
        sa.Column(
            "work_mode",
            _enum("opportunity_work_mode", "remote", "hybrid", "onsite"),
            nullable=True,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column(
            "employment_type",
            _enum(
                "employment_type",
                "full_time",
                "part_time",
                "internship",
                "contract",
            ),
            nullable=True,
        ),
        sa.Column("comp_min", sa.Numeric(12, 2), nullable=True),
        sa.Column("comp_max", sa.Numeric(12, 2), nullable=True),
        sa.Column("comp_currency", sa.String(length=8), nullable=True),
        sa.Column(
            "comp_period", _enum("comp_period", "hour", "month", "year"), nullable=True
        ),
        sa.Column("openings", sa.Integer(), nullable=True),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.CheckConstraint(
            "btrim(title) <> ''", name=op.f("ck_opportunities_title_not_blank")
        ),
        # An inverted range is a data-entry error, not a listing.
        sa.CheckConstraint(
            "comp_min IS NULL OR comp_max IS NULL OR comp_max >= comp_min",
            name=op.f("ck_opportunities_comp_range_ordered"),
        ),
        sa.CheckConstraint(
            "comp_min IS NULL OR comp_min >= 0",
            name=op.f("ck_opportunities_comp_min_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
            name=op.f("fk_opportunities_company_id_companies"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunities")),
        sa.UniqueConstraint("slug", name=op.f("uq_opportunities_slug")),
    )
    # §14.10's `(status, published_at DESC)` — "published, newest first" is exactly
    # this predicate plus this ordering.
    op.create_index(
        "ix_opportunities_status_published_at",
        "opportunities",
        ["status", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_opportunities_company_id", "opportunities", ["company_id"], unique=False
    )

    op.create_table(
        "opportunity_requirements",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("skill_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind", _enum("requirement_kind", "required", "preferred"), nullable=False
        ),
        # Free text, per §14.9's "min_level text NULL".
        sa.Column("min_level", sa.String(length=50), nullable=True),
        sa.Column("importance", sa.String(length=50), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
            name=op.f("fk_opportunity_requirements_opportunity_id_opportunities"),
            ondelete="CASCADE",
        ),
        # §14.9: RESTRICT — a catalogue skill a live posting names is pinned.
        sa.ForeignKeyConstraint(
            ["skill_id"],
            ["skills.id"],
            name=op.f("fk_opportunity_requirements_skill_id_skills"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_requirements")),
    )
    op.create_index(
        "ix_opportunity_requirements_opportunity_id",
        "opportunity_requirements",
        ["opportunity_id"],
        unique=False,
    )

    # --- the story links Phase 8 deferred ---------------------------------------
    #
    # ADD COLUMN, not a table rebuild: existing rows keep their identity and start
    # NULL, which satisfies the CHECK below for every `platform` story.
    op.add_column("stories", sa.Column("company_id", sa.UUID(), nullable=True))
    op.add_column("stories", sa.Column("opportunity_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_stories_company_id_companies",
        "stories",
        "companies",
        ["company_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_stories_opportunity_id_opportunities",
        "stories",
        "opportunities",
        ["opportunity_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # §14.10's rule, now expressible. See the module docstring.
    #
    # The name is passed **bare** on purpose. `create_check_constraint` runs it
    # through `Base.metadata`'s naming convention (`ck_%(table_name)s_%(constraint_
    # name)s`), so passing an already-prefixed `ck_stories_...` would produce
    # `ck_stories_ck_stories_...` — which is what an earlier draft of this file did,
    # leaving the database disagreeing with the ORM model that declares it. The
    # sibling constraints above use `op.f(...)` instead, which marks a name as final
    # and bypasses the convention; either spelling is fine, but they must not be
    # mixed for the same kind of constraint.
    op.create_check_constraint(
        "company_kind_matches_company",
        "stories",
        "(publisher_kind = 'company') = (company_id IS NOT NULL)",
    )


def downgrade() -> None:
    op.drop_constraint(
        "ck_stories_company_kind_matches_company", "stories", type_="check"
    )
    op.drop_constraint(
        "fk_stories_opportunity_id_opportunities", "stories", type_="foreignkey"
    )
    op.drop_constraint("fk_stories_company_id_companies", "stories", type_="foreignkey")
    op.drop_column("stories", "opportunity_id")
    op.drop_column("stories", "company_id")
    op.drop_index(
        "ix_opportunity_requirements_opportunity_id",
        table_name="opportunity_requirements",
    )
    op.drop_table("opportunity_requirements")
    op.drop_index("ix_opportunities_company_id", table_name="opportunities")
    op.drop_index("ix_opportunities_status_published_at", table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_index("ix_company_members_user_id_status", table_name="company_members")
    op.drop_index(
        "uq_company_members_one_owner",
        table_name="company_members",
        postgresql_where=sa.text("role = 'owner'"),
    )
    op.drop_table("company_members")
    op.drop_index("ix_companies_status", table_name="companies")
    op.drop_table("companies")
