"""Phase 6 — notifications.

One table (§14.7), and the two indexes the specification names individually.
Nothing else is created or touched: no earlier migration is modified, and no
column of any existing table is altered.

**``is_read``, and no ``read_at``.** §13.2 says "``is_read`` is a boolean on the
row" and §14.7 lists exactly that column. Every notification system grows a
``read_at`` eventually; V1 has no feature that reads it, so adding it here would
be a column the specification does not describe and nothing would ever populate.

**``actor_id`` is SET NULL and ``user_id`` is CASCADE, and the asymmetry is the
design.** §13.4: "Do **not** cascade-delete notifications when the actor's
content is deleted — the recipient still needs to know something happened, with
``actor`` rendered as null/anonymous." §14 confirms the intent: "`actor_id` is
`SET NULL`, not `CASCADE`, precisely so §13.4 holds." So removing an account takes
its notifications *to other people* down with it, and those rows survive with a
null actor.

``user_id`` — the **recipient** — is the opposite, and correctly so: a
notification is its recipient's own mail, and nobody has a legitimate interest in
another account's inbox. §14's rule that "CASCADE [is used] only for true
children" is what puts a notification in that column at all.

**No foreign key on ``target_id``.** It names a row owned by another domain (a
connection, a conversation) and §14.7 declares no constraint on it. A key here
would make this table a circular dependency on the phases that own those tables,
and would break outright for a future target type that has no table. §13.4's "a
notification points at a row that may later be deleted" is only expressible
because there is nothing to violate when it does.

**``type`` is a CHECK, not a native PostgreSQL ``ENUM``** — declared as
``sa.Enum(..., native_enum=False, create_constraint=True)``, which is how
``connections.status`` and every other vocabulary in this schema is declared, so
``pg_enum`` and this migration produce the same column. A native enum cannot gain
a value without ``ALTER TYPE`` and a lock, and §13.1's registry is expected to
grow when §8 and §9 land. The CHECK is generated by ``sa.Enum`` rather than
written out as a separate ``CheckConstraint``: two hand-written copies of one
vocabulary is two places for the next type to be forgotten.

**Both indexes are load-bearing and neither substitutes for the other.** The
partial one (``WHERE is_read = false``) serves ``?unread_only=true`` and the
unread count; the full one is the list's sort key ``(user_id, created_at, id)``.
The predicate is literal text because a partial index's predicate must be
immutable for the planner to use it at all. ``id`` is in the full index because
timestamps are not unique, and §13.3 pages on ``(created_at, id) DESC``: without
the tiebreak two rows sharing a timestamp could return in a different order on a
re-read, which is the duplicate-across-pages bug keyset exists to prevent.

Reversible: ``downgrade`` drops the indexes and the table, and touches nothing an
earlier phase created.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "b91d47e0c6a3"
down_revision: str | None = "744983a39587"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "notifications",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "connection_request",
                "connection_accepted",
                "message",
                "system",
                name="notification_type",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("target_type", sa.String(length=50), nullable=True),
        sa.Column("target_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), server_default="false", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),

        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_notifications_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
        comment=(
            "One event addressed to one recipient. actor_id is SET NULL (§13.4)."
        ),
    )

    # §14.7's partial index — the unread query and the unread count.
    op.create_index(
        "ix_notifications_user_id_created_at_unread",
        "notifications",
        ["user_id", "created_at"],
        unique=False,
        postgresql_where=sa.text("is_read = false"),
    )
    # §14.7's full index — the list's sort key.
    op.create_index(
        "ix_notifications_user_id_created_at_id",
        "notifications",
        ["user_id", "created_at", "id"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_notifications_user_id_created_at_id",
        table_name="notifications",
    )
    op.drop_index(
        "ix_notifications_user_id_created_at_unread",
        table_name="notifications",
    )
    op.drop_table("notifications")
